apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: inventory-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::416430293265:role/eksctl-nexmart-eks-addon-iamserviceaccount-in-Role1-yZgUDSySO2uR