apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      serviceAccountName: product-catalog
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
          effect: NoSchedule
      containers:
        - name: product-catalog
          image: 416430293265.dkr.ecr.ap-southeast-1.amazonaws.com/nexmart/product-catalog:a511625eb238d5fff4fac8aef364834fafc19425
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://adot-collector:4317
          envFrom:
            - secretRef:
                name: product-catalog-db-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10