apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-catalog
  namespace: product-catalog
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::416430293265:role/nexmart-product-catalog