apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: order-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::416430293265:role/eksctl-nexmart-eks-addon-iamserviceaccount-or-Role1-JNWUejZiVQjc