apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohripan/Nextmart.git
    targetRevision: HEAD
    path: k8s/base/product-catalog
    plugin:
      name: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: product-catalog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true